from utils import *
print("시작합니다.")
print("이름을 입력해 주세요: ")
name = input()
setName(name)
print("-"*50)
print("처음 이미지 등록을 시작합니다.")
data1 = open("TestCheck.jpg", 'rb')
print(data1)
createMainImage(data1)
print("성공했습니다.")
print("얼굴 인식을 위해 사진을 찍어주십시요")
data2 = open("TestImage.jpg", 'rb')
getSecondImage(data2)
print('-'*50)
compare()